name: hyper_ui
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <=3.3.2'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  google_sign_in: ^5.4.3
  intl: ^0.17.0
  google_fonts: ^3.0.1
  material_design_icons_flutter: ^5.0.6996
  image_picker: ^0.8.5+3
  file_picker: ^5.2.2
  uuid: ^3.0.6
  flutter_image_compress: ^1.1.3
  cached_network_image: ^3.2.2
  permission_handler: ^10.0.2
  geolocator: ^9.0.2
  flutter_map: ^3.0.0
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  blur: ^3.1.0
  flutter_svg: ^1.1.5
  custom_clippers: ^2.0.0
  badges: ^2.0.3
  flutter_markdown: ^0.6.12
  dotted_border: ^2.0.0+3
  hive: ^2.2.3
  faker_dart: ^0.1.11
  syncfusion_flutter_charts: ^20.3.58
  bitsdojo_window: ^0.1.5
  mobile_scanner: ^2.1.0
  qr_flutter: ^4.0.0
  path_provider: ^2.0.11
  flutter_animate: ^3.1.0
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^8.2.0
  dio: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/font/
    - assets/icon/
    - assets/image/